# Generated by Django 3.2.8 on 2021-10-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_name', models.CharField(max_length=100, unique=True)),
                ('total_unit', models.IntegerField()),
                ('total_progress', models.IntegerField(default=0)),
                ('left_unit', models.IntegerField()),
                ('left_day', models.IntegerField()),
                ('every_day_to_do_unit', models.IntegerField()),
                ('completed_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='LearningDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('every_day_unit', models.IntegerField()),
                ('learning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learning')),
            ],
        ),
    ]
