# Generated by Django 3.2.8 on 2021-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='progress_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
