# Generated by Django 3.2.8 on 2021-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_date_learningdetail_expired_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningdetail',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
