# Generated by Django 3.2.8 on 2021-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_rename_every_day_unit_learningdetail_day_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdetail',
            name='day_progress',
            field=models.IntegerField(default=0),
        ),
    ]
