# Generated by Django 3.2.8 on 2021-11-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_learning_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='category',
        ),
    ]
