# Generated by Django 3.2.8 on 2021-11-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20211118_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='group_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='learning',
            name='group_order',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
