# Generated by Django 3.2.8 on 2021-11-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20211118_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='group_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='group_order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
