# Generated by Django 3.2.8 on 2021-11-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_auto_20211118_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='group_order',
            field=models.IntegerField(null=True),
        ),
    ]
