# Generated by Django 3.2.8 on 2021-11-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_alter_learning_group_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, null=True)),
                ('group_order', models.IntegerField(null=True)),
                ('learning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learning')),
            ],
        ),
    ]
