# Generated by Django 3.2.8 on 2021-11-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_learninggroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='group_order',
        ),
    ]
