# Generated by Django 3.2.8 on 2021-11-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_auto_20211118_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninggroup',
            name='group_name',
        ),
    ]
