# Generated by Django 3.2.8 on 2021-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_remove_learninggroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggroup',
            name='group_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
