# Generated by Django 3.2.8 on 2021-11-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_learninggroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninggroup',
            name='learning',
        ),
        migrations.AddField(
            model_name='learning',
            name='learning_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learninggroup'),
        ),
    ]
