# Generated by Django 3.2.8 on 2021-11-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_auto_20211118_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggroup',
            name='group_task_order',
            field=models.IntegerField(null=True),
        ),
    ]
