# Generated by Django 3.2.8 on 2021-11-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_learninggroup_group_task_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='learning_group',
            new_name='group',
        ),
    ]
