# Generated by Django 3.2.8 on 2021-11-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_remove_learning_progress_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningdetail',
            name='learning',
        ),
        migrations.AddField(
            model_name='learning',
            name='learning_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningdetail'),
        ),
    ]
