# Generated by Django 3.2.8 on 2021-11-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_auto_20211123_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='completed',
        ),
    ]
